NOTE : Works with all available python packages in the module, check using conda list command
For conda env creation we recommend apps/anaconda/3EnvCreation module
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2ba8f411b390>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pytorch-fid/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2ba8f4199940>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pytorch-fid/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2ba8f41999e8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pytorch-fid/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2ba8f41992e8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/pytorch-fid/
